/**
 * Scripted reference solutions, one per puzzle room (room-local coordinates).
 * They document the intended solution and let tests prove every room is solvable.
 */
const laserOff = (id) => (sim, room) => !room.byId[id].active;

export const SOLUTIONS = [
  // Room 1: hold the plate for a cycle; Echo 1 holds it while you pass.
  [
    { goto: [-4.5, 2.5] },
    { waitRoom: 15.05 },
    { goto: [0, 0.1] },
    { waitDoor: 'd1' },
    { goto: [0, -2.4] },
    { goto: [1.6, -3] },
    { interact: 'core' },
    { exit: true },
  ],
  // Room 2: climb crate -> ledge, hold the plate; drop down and pass while Echo 1 holds it.
  [
    { goto: [-3.2, 4.5], sprint: false },
    { goto: [-4.4, 4.5], jump: true, sprint: false },
    { goto: [-6.5, 4.5], jump: true, sprint: false },
    { goto: [-6.5, 4.5], sprint: false, tol: 0.15 },
    { waitRoom: 15.05 },
    { goto: [-3.5, 1.5] },
    { goto: [0, -1.9] },
    { waitDoor: 'd1' },
    { goto: [0, -4.5] },
    { goto: [1.8, -5.2] },
    { interact: 'core' },
    { exit: true },
  ],
  // Room 3: hold the plate for a cycle; Echo 1 holds it and the laser grid switches off.
  [
    { goto: [5, 1.5] },
    { waitRoom: 15.05 },
    { goto: [0, -1.6] },
    { until: laserOff('grid') },
    { goto: [0, -4.6] },
    { goto: [-1.8, -5.0] },
    { interact: 'core' },
    { exit: true },
  ],
  // Room 4: dash onto the plate between laser pulses; next cycle freeze Echo 1 on it from the gates.
  [
    { goto: [-3, 6.4] },
    { waitRoom: 4 },
    { until: (sim, room) => !room.byId.field.active && room.byId.field.pulseRemaining() > 1.4 },
    { goto: [-3, 3], tol: 0.25 },
    { wait: 0.3 },
    { goto: [-3, 0.8] },
    { waitRoom: 15.05 },
    { goto: [0.2, -0.9] },
    { goto: [6, -0.8] },
    { waitEcho: 1, near: [-3, 3], tol: 0.5 },
    { freeze: 1 },
    { goto: [6, -9] },
    { goto: [3.2, -9.4] },
    { interact: 'core' },
    { exit: true },
  ],
  // Room 5: route Echo 1 around the furnace to the island plate; next cycle walk through the
  // furnace yourself so Echo 2 burns in it, then take the lift.
  [
    { goto: [-5, 4] },
    { goto: [0, 3.6] },
    { waitPlatform: 'mp1', phase: 'pauseA', within: 0.3 },
    { goto: [0, 1.5] },
    { waitPlatform: 'mp1', phase: 'pauseB' },
    { goto: [0, -7.2] },
    { goto: [0, -9], sprint: false },
    { waitRoom: 15.05 },
    { goto: [0, -6.6] },
    { waitPlatform: 'mp1', phase: 'pauseB', within: 0.3 },
    { goto: [0, -4.5] },
    { waitPlatform: 'mp1', phase: 'pauseA' },
    { goto: [0, 3.8] },
    { goto: [-2.5, 6.5], tol: 0.4 },
    { goto: [1.2, 9] },
    { waitPlatform: 'mp2', phase: 'pauseA', within: 0.3 },
    { goto: [3, 9], sprint: false },
    { waitPlatform: 'mp2', phase: 'pauseB' },
    { goto: [5.3, 9] },
    { waitDoor: 'd1' },
    { goto: [7.6, 9], sprint: false },
    { interact: 'core' },
    { goto: [5.3, 9] },
    { goto: [5, 5] },
    { goto: [0, 3.6] },
    { waitPlatform: 'mp1', phase: 'pauseA', within: 0.3 },
    { goto: [0, 1.5] },
    { waitPlatform: 'mp1', phase: 'pauseB' },
    { goto: [-6, -9] },
    { exit: true },
  ],
  // Room 6: jump a noisy east-lane decoy, then record the alcove plate while Echo 1 draws the Hunter.
  [
    { jumpOver: [7.6, -2.4], at: 2.5 },
    { goto: [6.5, -2.6], sprint: false },
    { waitRoom: 15.05 },
    { goto: [-2.2, 6.4], jump: true, sprint: false },
    { interact: 's2' },
    { goto: [-4.5, 5.8], sprint: false },
    { jumpOver: [-4.5, 0.5], at: 1.5 },
    { goto: [-5, -2.5], sprint: false },
    { goto: [-8, -2.5], sprint: false },
    { waitRoom: 30.05 },
    { goto: [0, -3.5], sprint: false },
    { until: (sim, room) => !room.byId.l1.active },
    { goto: [0, -6], sprint: false },
    { goto: [1.9, -6.4], sprint: false },
    { interact: 'core' },
    { exit: true },
  ],
  // Room 7: hold plates A and B, then delete a 2 s detour so Echo 3 catches the alcove door.
  [
    { goto: [-9, 4] },
    { waitRoom: 15.05 },
    { goto: [9, 4] },
    { waitRoom: 30.05 },
    { goto: [0, 5.8] },
    { interact: 'routeBreaker' },
    { wait: 1.0 },
    { goto: [3.5, 5.8] },
    { wait: 1.0 },
    { goto: [7.5, -1.8] },
    { interact: 'tb1' },
    { goto: [10.5, -2.8] },
    { goto: [10.2, -5.6] },
    { waitRoom: 45.05 },
    { edit: 'delete', at: 1.0 },
    { interact: 'tb2' },
    { goto: [10.5, -2.0] },
    { goto: [6, -2.0] },
    { goto: [0, -5.6] },
    { waitDoor: 'd1' },
    { goto: [0, -8.3] },
    { goto: [-2.6, -8.4] },
    { interact: 'core' },
    { exit: true },
  ],
  // Room 8: plate -> relay A -> island button -> relay B -> sync switches -> reactor.
  [
    { goto: [6, 10] },
    { waitRoom: 15.05 },
    { goto: [-8.8, 5] },
    { until: laserOff('l1') },
    { goto: [-14.3, 5] },
    { interact: 'n1' },
    { goto: [-8.8, 5] },
    { goto: [7.4, 0] },
    { waitPlatform: 'mp1', phase: 'pauseA', within: 0.3 },
    { goto: [9.5, 0] },
    { waitPlatform: 'mp1', phase: 'pauseB' },
    { goto: [15, 0] },
    { waitRoom: 43.5 },
    { interact: 'tb1' },
    { waitPlatform: 'mp1', phase: 'pauseB', within: 0.3 },
    { goto: [12.5, 0] },
    { waitPlatform: 'mp1', phase: 'pauseA' },
    { goto: [7.2, 0] },
    { goto: [0, -4.8] },
    { waitDoor: 'td1' },
    { goto: [0, -7.8] },
    { goto: [3.5, -9.8] },
    { interact: 'n2' },
    { goto: [2, -8.4], sprint: false },
    { waitRoom: 61 },
    { interact: 'tb2' },
    { goto: [0, -8.0] },
    { goto: [0, -4.5] },
    { goto: [15, -4.5] },
    { waitRoom: 70 },
    { interact: 'sw2' },
    { goto: [-15, -4.5] },
    { waitRoom: 85 },
    { interact: 'sw1' },
    { goto: [-11, -4.6] },
    { waitDoor: 'dCore' },
    { goto: [-11, -8] },
    { goto: [-12.5, -9.6] },
    { interact: 'reactor' },
    { exit: true, timeout: 60 },
  ],
];
